# Generated by Django 3.1.2 on 2021-01-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210114_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='book_cover_folder/None/no-img.jpg', upload_to='book_cover_folder'),
        ),
    ]
